---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 104.155.0.20
      ansible_port: 22
      ansible_ssh_user: it21906
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: 104.155.0.20
      ansible_port: 22
      ansible_ssh_user: it21906
  vars:
    ansible_python_interpreter: /usr/bin/python3
