---
- hosts: deploymentservers

  vars:
    app_dir: "{{user_dir}}/userSystem"
    
    git_repo_url: "https://github.com/it21918/django_userSystem.git"
    git_repo_branch: "kubernates_django_userSystem"

  tasks:

  - name: print user_dir
    debug:
      msg: "user dir is {{user_dir}}"

  - name: Run whoami without become.
    command: whoami
    changed_when: false
    become: false
    register: whoami

  - name: Set a fact with the user name.
    set_fact:
      login_user: "{{ whoami.stdout }}"

  - name: print user name
    debug:
      msg: "login user is {{login_user}}"

  - name: print user dir
    debug:
      msg: "login dir is {{user_dir}}"

  - name: ensure github.com is a known host
    lineinfile:
      dest: "{{user_dir}}/.ssh/known_hosts"
      create: yes
      state: present
      line: "{{lookup('pipe', 'ssh-keyscan -t rsa github.com')}}"
      regexp: "^github\\.com"

  - name: clone django project
    git:
      repo: "{{git_repo_url}}"
      version: "{{git_repo_branch}}"
      clone: yes
      force: yes
      dest: "{{app_dir}}"
    changed_when: true
  


  - name: copy env file
    shell : "cp {{app_dir}}/userSystem/userSystem/.env.example {{app_dir}}/userSystem/userSystem/.env"

  
  - name: Get my public IP
    ipify_facts:

  - debug: var=ipify_public_ip

 

  - name: add ip in django ALLOWED_HOSTS
    lineinfile:
      dest: "{{app_dir}}/userSystem/userSystem/settings.py"
      regexp: "^ALLOWED_HOSTS ="
      line: "ALLOWED_HOSTS = ['{{ipify_public_ip}}','127.0.1.1','localhost','10.3.0.4']"
      state: present


  - name: django deploy_yml
    command: microk8s.kubectl apply -f k8s/django/django2-deployment.yaml
    args:
      chdir: /home/it21906/userSystem

  - name: django clip
    command: microk8s.kubectl apply -f k8s/django/django2-clip.yaml
    args:
      chdir: /home/it21906/userSystem

  - name: django pvc
    command: microk8s.kubectl apply -f k8s/django/django2-ingress.yaml
    args:
      chdir: /home/it21906/userSystem


  - name: mailhog set_up
    command: microk8s.kubectl apply -f k8s/django/mailhog.yaml
    args:
      chdir: /home/it21906/userSystem
      
  - name: fix readonly
    command : "chown it21906 db.sqlite3"
    args:
      chdir: /home/it21906/userSystem/userSystem
      
         
  - name: Restart
    ansible.builtin.reboot:
      reboot_timeout: 3600
      
  become: yes
  become_user: root
