- hosts: deploymentservers
  roles:
    - role:  jebovic.mailhog
      become: yes

  tasks:
  - name: copy mailhog service file
    template:
      src: ../files/mailhog.service
      dest: "/etc/systemd/system/mailhog.service"
    become: yes
    become_user: root
    
  - name: start mailhog 
    shell: "systemctl start mailhog"
    become: yes
    become_user: root
    
  


